### ISSUE TITLE
stream:/movie/technique/wonderwing.webm is missing

### ISSUE THREAD

**Issue by trainboy2019** [ultimate-research/archive-hashes#1]
The file stream:/movie/technique/wonderwing.webm is missing, this leads to index out of range errors.

**Comment by RandomTBush** [comment]
Late reply, but it seems that it's actually a bug with CrossArc, not the hashes list here. *All* of the "technique" videos are off by one currently, even the first one, "absorption_recovery.webm" ends up being the one for "air_escape_move.webm" if you try extracting it. I did inform Ploaj about it on a couple of occasions, but no reply yet.

**Comment by jam1garner** [comment]
I'd argue this is irrelevant and should be posted as an issue on CrossArc's repo
